const SG_BANKS_LIST = [
  'Development Bank of Singapore',
  'United Overseas Bank',
  'Maybank Singapore Limited',
  'Oversea-Chinese Banking Corporation Limited',
  'Citibank NA',
  'Citibank Singapore',
  'Standard Chartered Bank',
  'Australia and New Zealand Bank Group',
  'CIMB Bank Berhad',
  'Deutsche bank AG',
  'Far Eastern Bank Ltd',
  'HSBC (Corporate)',
  'HSBC (Personal)',
  'RHB Bank Berhad',
  'Sumitomo Mitsui Banking Corporation',
  'The Royal Bank of Scotland N.V',
  'POSB',
  'Bank of China',
  'Bank of Tokyo-Mitsubshi UFJ',
  'BNP PARIBAS',
  'HL BANK',
  'Mizuho Bank',
  'BANK OF EAST ASIA LTD',
  'Industrial and Commercial Bank of China',
  'Sing Investments & Finance Limited',
  'JP Morgan Chase Bank',
  'ICICI Bank Limited',
  'GPay Network (S) Pte Ltd',
  'Liquid Group Pte Ltd',
  'MatchMove Pay Pte Ltd',
  'SingCash Pte Ltd',
  'TransferWise Singapore Pte Ltd',
  'Xfers Pte Ltd',
  'Green Link Digital Bank Pte Ltd',
  'GXS Bank Pte Ltd',
  'Malayan Banking Berhad',
  'State Bank of India',
  'MariBank Singapore Private Limited',
  'Trust Bank Singapore Limited',
  'ANEXT BANK PTE. LTD.',
  'NIUM PTE LTD',
];

export const SG_BANKS = SG_BANKS_LIST.sort();
